# XBoard 配置文件
# 复制此文件为 xboard.config.yaml 并修改相应配置

xboard:
  # 后端提供商类型
  provider: mihomo
  
  # 远程配置源
  remote_config:
    sources:
      # 主配置源
      - name: redirect
        url: https://gh-proxy.com/https://raw.githubusercontent.com/yeyuqaq/yu/refs/heads/master/config.json
        priority: 100
      
      # 备用配置源（可选）
      #- name: gitee
       # url: https://gitee.com/user/repo/raw/branch/config.txt
       # priority: 90
        # Gitee源需要提供加密密钥
        #encryption_key: YOUR_ENCRYPTION_KEY_HERE
    
    # 请求超时时间（秒）
    timeout_seconds: 10
    
    # 最大重试次数
    max_retries: 3
    
    # 重试延迟（秒）
    retry_delay_seconds: 2
  
  # 延迟测试配置
  latency_test:
    # 测试 URL（可以改为你的测试地址）
    test_url: http://www.gstatic.com/generate_204
    timeout_seconds: 5
  
  # 域名竞速服务
  domain_service:
    # 是否启用
    enable: true
    
    # 缓存时间（分钟）
    cache_minutes: 2
    
    # 最大重试次数
    max_retries: 3
    
    # 单次测试超时（秒）
    test_timeout_seconds: 5
    
    # 最大并发测试数
    max_concurrent_tests: 10
  
  # SDK 配置
  sdk:
    # 超时时间（毫秒）
    timeout_milliseconds: 6000
    
    # 启用调试日志
    enable_debug_log: true
    
    # 初始化策略
    # race_fastest: 竞速模式（推荐）
    # default: 默认模式
    strategy: race_fastest
  
  # 日志配置
  log:
    # 是否启用
    enabled: true
    
    # 日志级别: debug, info, warning, error
    level: info
    
    # 日志前缀
    prefix: "[天际云]"
  
  # 应用信息
  app:
    # 登录页面显示的标题
    title: 天际云
    
    # 登录页面显示的网站地址
    website: tj1.djsy.xyz
  
  # 订阅配置
  subscription:
    # 是否优先使用加密订阅
    # true: 优先尝试加密订阅（自动启用竞速），失败后自动回退到普通订阅
    # false: 直接使用普通订阅（不使用竞速）
    prefer_encrypt: false
  
  # 安全与加密配置
  security:
    # 订阅解密密钥
    # 用于解密加密订阅数据，需要与后端配置一致
    decrypt_key: YOUR_DECRYPT_KEY_HERE
    
    # 响应混淆前缀（需要与后端 Caddy 反代配置保持一致）
    # 例如 Caddy 配置：replace "{\"status\"" "OBFS_PREFIX_{\"status\""
    # SDK 会自动检测响应是否包含此前缀，有则反混淆，无则直接解析
    # 如果后端没有使用混淆，设置为空字符串或 null
    obfuscation_prefix: YOUR_OBFS_PREFIX_
    
    # User-Agent 配置（域名竞速专用）
    # ⚠️ 重要：这些UA字符串与后端约定，修改可能导致功能异常
    user_agents:
      # API请求/域名竞速 UA（包含加密字符串用于 Caddy 认证）
      # 加密部分：YOUR_ENCRYPTED_TOKEN
      api_encrypted: Mozilla/5.0 (compatible; xiaoyetianji/1.0)
      
      # 域名竞速测试 UA
      domain_racing_test: YourApp/1.0 (Domain Racing Test)
    
    # TLS 证书配置
    certificate:
      # 证书文件路径（相对于 packages 目录）
      # 用于域名竞速的 HTTPS 连接验证
      path: flutter_xboard_sdk/assets/cer/client-cert.crt
      
      # 是否启用证书验证
      enabled: true

